import React from 'react';
import renderer, { act } from 'react-test-renderer';
import { StyleSheet } from 'react-native';
import { EventMembersCard } from '../src/components/EventMembersCard';
import { IconTextButton } from '../src/components/IconTextButton';
import { AppButton } from '../src/design-system/components/AppButton';
import { PaperFormInput } from '../src/components/PaperFormInput';
import { SelectableChipGroup } from '../src/components/SelectableChipGroup';
import { MirrorToggleRow } from '../src/components/MirrorToggleRow';
import { DestructiveConfirmationModal } from '../src/components/DestructiveConfirmationModal';
import { getTheme } from '../src/design-system/theme';
import { tokens } from '../src/design-system/tokens';
import { setLocale, t } from '../src/i18n';
import { addEventMemberApi, listEventMembersApi, removeEventMemberApi, updateEventMemberApi } from '../src/services/api/events';

jest.mock('@react-native-vector-icons/fontawesome6', () => 'Icon');
jest.mock('react-native-safe-area-context', () => ({ SafeAreaView: require('react-native').View, useSafeAreaInsets: () => ({ top: 62, bottom: 34, left: 0, right: 0 }) }));
jest.mock('../src/components/PaperFormInput', () => ({ PaperFormInput: 'Input' }));
const mockToast = jest.fn();
jest.mock('../src/providers/ToastProvider', () => ({ ToastViewport: () => null, useToast: () => ({ showToast: mockToast }) }));
jest.mock('../src/services/api/events', () => ({ addEventMemberApi: jest.fn(), listEventMembersApi: jest.fn(), removeEventMemberApi: jest.fn(), updateEventMemberApi: jest.fn() }));
const member = { id: '7', user: { id: '8', email: 'ana@example.com', name: 'Ana' }, role: { slug: 'cliente' }, status: 'active' };
const byId = (tree, type, id) => tree.root.findAllByType(type).find(node => node.props.testID === id);
beforeEach(() => {
  jest.clearAllMocks(); setLocale('es');
  listEventMembersApi.mockResolvedValue({ members: [] });
  for (const api of [addEventMemberApi, updateEventMemberApi, removeEventMemberApi]) api.mockResolvedValue({ members: [] });
});
afterEach(() => setLocale('es'));
test.each([['light', 'es'], ['dark', 'es'], ['light', 'en'], ['dark', 'en']])('adds by email with existing roles, tokens and safe modal in %s/%s', async (mode, locale) => {
  setLocale(locale); let tree;
  await act(async () => { tree = renderer.create(<EventMembersCard eventId="20" theme={getTheme(mode)} userId="1" />); });
  expect(listEventMembersApi).toHaveBeenCalledWith('20');
  expect(StyleSheet.flatten(tree.root.findByProps({ testID: 'event-members' }).props.style).gap).toBe(tokens.spacing.md);
  act(() => byId(tree, IconTextButton, 'event-member-add').props.onPress());
  const save = () => byId(tree, AppButton, 'event-member-save');
  expect(save().props.disabled).toBe(true);
  const input = tree.root.findByType(PaperFormInput);
  expect(input.props).toMatchObject({ label: t('event_member_email'), keyboardType: 'email-address', autoCapitalize: 'none' });
  expect(tree.root.findByType(SelectableChipGroup).props.options.map(option => option.value)).toEqual(['admin', 'operario', 'cliente']);
  act(() => { input.props.onChangeText(' ANA@Example.com '); tree.root.findByType(SelectableChipGroup).props.onChange('operario'); });
  expect(save().props.disabled).toBe(false);
  await act(async () => save().props.onPress());
  expect(addEventMemberApi).toHaveBeenCalledWith('20', { email: 'ana@example.com', roleSlug: 'operario' });
  expect(mockToast).toHaveBeenCalledWith({ type: 'success', message: t('event_members_saved') });
  act(() => tree.unmount());
});
test('unknown email keeps input, explains registration and blocks duplicate submission', async () => {
  let fail; addEventMemberApi.mockImplementation(() => new Promise((_resolve, reject) => { fail = reject; }));
  let tree; await act(async () => { tree = renderer.create(<EventMembersCard eventId="20" theme={getTheme('dark')} userId="1" />); });
  act(() => byId(tree, IconTextButton, 'event-member-add').props.onPress());
  act(() => tree.root.findByType(PaperFormInput).props.onChangeText('new@example.com'));
  act(() => { const save = byId(tree, AppButton, 'event-member-save'); save.props.onPress(); save.props.onPress(); });
  expect(addEventMemberApi).toHaveBeenCalledTimes(1);
  expect(byId(tree, AppButton, 'event-member-save').props.disabled).toBe(true);
  await act(async () => fail(Object.assign(new Error('Not found'), { code: 'EVENT_MEMBER_REGISTER_FIRST' })));
  expect(tree.root.findByType(PaperFormInput).props).toMatchObject({ value: 'new@example.com', errorText: t('event_member_register_first') });
  act(() => tree.unmount());
});
test('edits the event role/status, prevents editing email and confirms removing only that assignment', async () => {
  listEventMembersApi.mockResolvedValue({ members: [member] }); updateEventMemberApi.mockResolvedValue({ members: [member] });
  let tree; await act(async () => { tree = renderer.create(<EventMembersCard eventId="20" theme={getTheme('light')} userId="1" />); });
  act(() => byId(tree, IconTextButton, 'event-member-edit-7').props.onPress());
  expect(tree.root.findByType(PaperFormInput).props.editable).toBe(false);
  act(() => { tree.root.findByType(SelectableChipGroup).props.onChange('admin'); tree.root.findByType(MirrorToggleRow).props.onChange(false); });
  await act(async () => byId(tree, AppButton, 'event-member-save').props.onPress());
  expect(updateEventMemberApi).toHaveBeenCalledWith('20', '7', { roleSlug: 'admin', status: 'suspended' });
  act(() => byId(tree, IconTextButton, 'event-member-remove-7').props.onPress());
  expect(removeEventMemberApi).not.toHaveBeenCalled();
  expect(tree.root.findByType(DestructiveConfirmationModal).props.visible).toBe(true);
  await act(async () => tree.root.findByType(DestructiveConfirmationModal).props.onConfirm());
  expect(removeEventMemberApi).toHaveBeenCalledWith('20', '7');
  act(() => tree.unmount());
});
test('does not offer editing/removing your own assignment', async () => {
  listEventMembersApi.mockResolvedValue({ members: [member] });
  let tree; await act(async () => { tree = renderer.create(<EventMembersCard eventId="20" theme={getTheme('dark')} userId="8" />); });
  expect(byId(tree, IconTextButton, 'event-member-edit-7')).toBeUndefined();
  expect(byId(tree, IconTextButton, 'event-member-remove-7')).toBeUndefined();
  act(() => tree.unmount());
});
