import React from 'react';
import { ScrollView, StyleSheet, Switch } from 'react-native';
import { TransferBankList } from '../src/components/TransferBankCard';
import renderer, { act } from 'react-test-renderer';
import { TransferBankCarousel } from '../src/components/TransferBankCarousel';
import { ManagementCard } from '../src/components/ManagementCard';
import { getTheme } from '../src/design-system/theme';
import { tokens } from '../src/design-system/tokens';
import { setLocale } from '../src/i18n';
import Clipboard from '@react-native-clipboard/clipboard';
import { CopyActionButton } from '../src/components/CopyActionButton';
import { IconTextButton } from '../src/components/IconTextButton';
jest.mock('@react-native-vector-icons/fontawesome6', () => 'Icon');
jest.mock('../src/providers/ToastProvider', () => ({ useToast: () => ({ showToast: jest.fn() }) }));
jest.mock('react-native-paper', () => ({ Checkbox: { Item: 'CheckboxItem' } }));
const banks = [{ id: '1', bank: 'Bank with a long name', holder: 'Holder', identification: '001', accountNumber: '000123', accountType: 'Savings', active: true }, { id: '2', bank: 'Second bank', active: false }];
afterEach(() => setLocale('es'));

describe.each(['light', 'dark'])('transfer card reel in %s', mode => {
  const theme = getTheme(mode);
  it.each([320, 375, 768, 1024])('sizes cards within %s px and matches the filters edge fades', width => {
    let tree;
    act(() => { tree = renderer.create(<TransferBankCarousel theme={theme} banks={banks} backgroundColor={theme.surface} />); });
    const scroll = () => tree.root.findByType(ScrollView);
    const move = x => act(() => scroll().props.onScroll({ nativeEvent: { contentOffset: { x }, layoutMeasurement: { width }, contentSize: { width: width * 2 } } }));
    act(() => scroll().props.onLayout({ nativeEvent: { layout: { width } } }));
    expect(scroll().props.horizontal).toBe(true);
    const card = tree.root.findByProps({ testID: 'transfer-banks-card-1' });
    expect(StyleSheet.flatten(card.props.style).width).toBeLessThanOrEqual(width);
    expect(StyleSheet.flatten(card.props.style).flexShrink).toBe(0);
    move(width / 2);
    const fades = tree.root.findAllByType('LinearGradient');
    expect(fades.map(fade => fade.props.colors)).toEqual([[theme.surface, `${theme.surface}00`], [`${theme.surface}00`, theme.surface]]);
    fades.forEach(fade => {
      expect(fade.props.pointerEvents).toBe('none');
      expect(StyleSheet.flatten(fade.props.style).width).toBe(tokens.spacing.lg);
    });
    act(() => scroll().props.onContentSizeChange(width - 1));
    expect(tree.root.findAllByType('LinearGradient')).toHaveLength(0);
    act(() => tree.unmount());
  });
  it('exposes independent active checks and edits without changing local state optimistically', () => {
    setLocale(mode === 'light' ? 'es' : 'en');
    const onToggle = jest.fn(), onEdit = jest.fn();
    let tree;
    act(() => { tree = renderer.create(<TransferBankCarousel theme={theme} banks={banks} onToggle={onToggle} onEdit={onEdit} />); });
    const checks = tree.root.findAllByType(Switch);
    expect(checks.map(check => check.props.value)).toEqual([true, false]);
    act(() => checks[1].props.onValueChange(true));
    expect(onToggle).toHaveBeenCalledWith(banks[1], true);
    expect(checks[1].props.value).toBe(false);
    act(() => tree.root.findByProps({ testID: 'transfer-banks-edit-1' }).props.onPress());
    expect(onEdit).toHaveBeenCalledWith(banks[0]);
    act(() => tree.unmount());
  });
  it('uses full-width cards in the admin list, with stable labeled switches', () => {
    let tree;
    act(() => { tree = renderer.create(<TransferBankList banks={banks} theme={theme} onToggle={jest.fn()} onEdit={jest.fn()} />); });
    expect(tree.root.findAllByType(ScrollView)).toHaveLength(0);
    expect(tree.root.findAllByType(ManagementCard)).toHaveLength(2);
    const toggles = tree.root.findAllByType(Switch);
    expect(toggles[0].props.accessibilityLabel).toBe(toggles[1].props.accessibilityLabel);
    const copy = tree.root.findByType(CopyActionButton);
    expect(copy.props).toMatchObject({ value: '000123', iconOnly: true });
    act(() => copy.findByType(IconTextButton).props.onPress());
    expect(Clipboard.setString).toHaveBeenLastCalledWith('000123');
    act(() => tree.unmount());
  });
  it('separates destination selection from administrative activation and supports historical read-only cards', () => {
    const onSelect = jest.fn();
    let tree;
    act(() => { tree = renderer.create(<TransferBankCarousel theme={theme} banks={[banks[0]]} selectedId="1" onSelect={onSelect} />); });
    expect(tree.root.findAllByType('CheckboxItem')).toHaveLength(0);
    expect(tree.root.findByProps({ testID: 'transfer-banks-select-1' }).props.selected).toBe(true);
    act(() => tree.root.findByProps({ testID: 'transfer-banks-select-1' }).props.onPress());
    expect(onSelect).toHaveBeenCalledWith('1');
    act(() => tree.update(<TransferBankCarousel theme={theme} banks={[banks[0]]} />));
    expect(tree.root.findByType(ManagementCard).props.actions).toBeNull();
    expect(tree.root.findByType(CopyActionButton).props.value).toBe('000123');
    act(() => tree.unmount());
  });
});
